namespace: intel
name: sdptool
version: 2.0.0
readme: README.md
authors:
- Yeshaswi M R Gowda <yeshaswi.m.r.gowda@intel.com>
- Mohammed Mujahid Ul Islam <mohammed.mujahid.ul.islam@intel.com>

description: Intel(R) SDP Tool Ansible plugin.
  Intel(R) SDP Tool Ansible plugin is an Ansible action plugin, which provides
  Intel(R) Server Debug and Provisioning Tool (SDP Tool) capabilities in an
  action plugin. The plugin enables all the functionalities of the SDP Tool.
  The inventory file can feed in the required paths for the appropriate files.
  A sample of the inventory file is available in the project which can be 
  customized and used. A sample playbook is also provided to assist in writing
  a customized playbook. Please find more information on the capabilities /
  usage of the SDP Tool in the following link.
  https://downloadcenter.intel.com/download/30410/Intel-Server-Debug-and-Provisioning-Tool-Intel-SDP-Tool-

license:
- GPL-3.0+

license_file: ''

tags: ['intel', 'sdptool', 'bmc', 'bios', 'fru', 'sdr', 'me', 'redfish', 'redfish api', 'update', 'server boards', 'automation', 'devops']

dependencies: {}

repository: https://github.com/intel/intel-sdptool-ansible-modules

homepage: https://github.com/intel/intel-sdptool-ansible-modules

issues: https://github.com/intel/intel-sdptool-ansible-modules/issues
