---
- name: Server Manage
  hosts: BMC
  collections:
    - intel.sdptool
  strategy: free
  environment:
    http_proxy: ""
    https_proxy: ""
    no_proxy: ""
  tasks:
    - name: CPU Information
      sdptool:
        action: "cpuinfo"
      register: output

    - name: SDPTool output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: System Information
      sdptool:
        action: "systeminfo"
      register: output

    - name: System Info Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: Set LAN Parameters
      sdptool:
        action: "setlan"
        args: 
          - 1
          - 1.2.3.4
          - 255.255.0.0
          - 1.2.3.1
          - 1.1.1.3
          - 1.1.1.4
      register: output

    - name: Set LAN Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: Get SEL
      sdptool:
        action: "sel"
        args: 
          - -f
          - /tmp/sel.log
      register: output

    - name: Get SEL Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: Set Biosconfig
      sdptool:
        action: "set_biosconfig_all"
      register: output

    - name: Get SEL Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: Update SUP
      sdptool:
        action: "update"
      register: output

    - name: Update Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: Custom Deploy
      sdptool:
        action: "custom_deploy"
      register: output

    - name: Custom Deploy Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: CUP Deploy
      sdptool:
        action: "cup_deploy"
      register: output

    - name: CUP Deploy Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: CUP Staged Deploy
      sdptool:
        action: "cup_deploy"
        args:
          - -staged
      register: output

    - name: CUP Deploy Output
      debug:
        msg: "{{ output.stdout_lines }}"

    - name: CUP Inspect
      sdptool:
        action: "cup_inspect"
      register: output

    - name: CUP Inspect Output
      debug:
        msg: "{{ output.stdout_lines }}"
